version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: dublin_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dublin_housing
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: dublin_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile.streamlit
    image: docker_streamlit
    container_name: dublin_streamlit
    restart: unless-stopped
    env_file:
      - ../.env           # optional; if present
    environment:
      PG_URL: ${PG_URL:-postgresql+psycopg2://postgres:postgres@postgres:5432/dublin_housing}
    depends_on:
      - postgres
    ports:
      - "8501:8501"

  dagster:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dagster
    image: docker_dagster
    container_name: dublin_dagster
    restart: unless-stopped
    env_file:
      - ../.env           # optional; if present
    environment:
      PG_URL: ${PG_URL:-postgresql+psycopg2://postgres:postgres@postgres:5432/dublin_housing}
    depends_on:
      - postgres
      - mongo
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  mongo_data: